### ISSUE TITLE
Action button Image

### ISSUE THREAD

**Issue by HarryWickham** [yordevs/yordle#5]
Currently on the keyboard the enter and backspace buttons are text: ↵ 🠔 but on some devices these will not look the same for example on a Samsung S8 the keyboard looks like:
![Screenshot_20220403-181534_DuckDuckGo](https://user-images.githubusercontent.com/51520004/161548264-eddf7308-3bed-4f20-b9bb-86bbecddc7be.jpg)
Changing them to SVGs or images would fix this.

**Comment by 4dambarr** [comment]
Fixed using react icons
